version: '3.8'

services:
  app:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - ..:/workspace:cached
    command: sleep infinity
    environment:
      - PYTHONPATH=/workspace
    # Uncomment if you need to connect to other services
    # networks:
    #   - devcontainer-network

  # Add additional services here if needed
  # For example, a database:
  # postgres:
  #   image: postgres:15
  #   restart: unless-stopped
  #   volumes:
  #     - postgres-data:/var/lib/postgresql/data
  #   environment:
  #     POSTGRES_USER: postgres
  #     POSTGRES_PASSWORD: postgres
  #     POSTGRES_DB: myapp
  #   networks:
  #     - devcontainer-network

# networks:
#   devcontainer-network:
#     driver: bridge

# volumes:
#   postgres-data: